### ISSUE TITLE
[Feature request] — Option to add emotions as nested tags

### ISSUE THREAD

**Issue by rushikb** [dartungar/obsidian-emotion-picker#1]
I love the idea behind this plugin, and it fits really well with how I journal too, I wonder if there's a way to add an option to insert emotions as tags or page titles. So #anger/angry — or [[angry]] — this would be similar to what you currently have to add with commas
![image](https://user-images.githubusercontent.com/6484525/148345154-29115b80-acf0-4c34-bd4f-bc5b9f641595.png)

**Comment by dartungar** [comment]
Some of your suggestions are implemented in v0.3. Thanks for them, by the way. :)
Nested tags are a bit more tricky but perhaps I'll get to them sometime this winter.

**Comment by angelinalblyth** [comment]
Apologies I opened another issue with the same request before seeing this closed one. If this isn't being worked on I may give it ago myself.

**Comment by dartungar** [comment]
@angelinalblyth you definetely may! time is a bit tight right now for me 👍
