### ISSUE TITLE
Picker doesn't seem to respond to x Close after running (iOS 16.2)

### ISSUE THREAD

**Issue by billga** [dartungar/obsidian-emotion-picker#10]
Running Emotion Picker 1.0.0, Obsidian for iOS 1.4.1, iOS 16.2, on an iPhone 13 Pro. 
Open any note, select the Emotions picker, then either select an entry (or not) and hit the X. 
Nothing Happens. 
The only way to get out of this is to kill the app and restart.
The entry did get put into the note.

**Comment by manuel-cerezo** [comment]
It's already solved (I suppose it was because an Obsidian update) :)

**Comment by dartungar** [comment]
TY @manueldevjour - I don't own an iPhone so I have no way of checking this. Closing the issue now.
