### ISSUE TITLE
Add translation based on current editor language

### ISSUE THREAD

**Issue by borisrorsvort** [dartungar/obsidian-emotion-picker#12]
That would be very nice to add translations. I guess French, Spanish,…

**Comment by dartungar** [comment]
@borisrorsvort I like the idea, but... see my question in https://github.com/dartungar/obsidian-emotion-picker/pull/11 . It remains unanswered for me still. Personally I'd like to keep the plugin as simple as possible.

**Comment by borisrorsvort** [comment]
@dartungar good for me! 🎉  as long as you can keep them categorised. I guess json then.
