### ISSUE TITLE
After closing down the vault all settings restored to default

### ISSUE THREAD

**Issue by FairySelkie** [dartungar/obsidian-emotion-picker#16]
Hello! I love your plugin so much, was super excited to find it!!! I started to use it and made my own list of emotions for my diary, and was extremely happy with that. But... After I closed the vault and opened it again - all my data has disappeared :( I tried to change to different languages and save new data there - it didn't work. Also, if I just delete a block from default setup, next time I open the vault it is back to default again. I would be very grateful if it could be fixed or find a way around - as I really would like to continue to use you nice plugin! Thank you!!

**Comment by dartungar** [comment]
@FairySelkie this should be fixed in 1.2.1.
