### ISSUE TITLE
[Feature Request] -- add emotions  / groups to picker

### ISSUE THREAD

**Issue by thecookiemomma** [dartungar/obsidian-emotion-picker#2]
Firstly, I want to say that I love this picker. I think it's amazing especially for daily notes to put how you're feeling in it. I did wonder if it would be possible to personalize it with more emotions / states for that specific use case.  If it is difficult, it's not an absolute need, but I would appreciate being able to add new ones or change out to help with recording my state each day.  
Thank you again for all the hard work on this plugin. I recently found it, and slapped it inside a button and made a lovely little "How am I" picker for my daily notes.

**Comment by dartungar** [comment]
I'm considering that, however it's a little more work and time is tight right now. 
(thanks for the kind words!)

**Comment by dartungar** [comment]
Hooray, I managed to carve out some time and do it.
Full customization available in https://github.com/dartungar/obsidian-emotion-picker/releases/tag/1.0.0.
