### ISSUE TITLE
Latest update will not install

### ISSUE THREAD

**Issue by spiritualgeek** [dartungar/obsidian-emotion-picker#4]
The latest update will not install

Even removing the plugin and re-adding it fails

**Comment by dartungar** [comment]
Due to a typo in version in manifest.json, Obsidian tries to download files for non-existent release. :(

I fixed this; it will be available once Obsidian updates plugin version (in 24 hours or less).

Sorry for the inconvenience!

**Comment by dartungar** [comment]
Things work as intended already. Cheers!
