### ISSUE TITLE
Option to add customised emotions

### ISSUE THREAD

**Issue by Bhuman-Patel** [dartungar/obsidian-emotion-picker#5]
Hey, It's really a great plugin, I have found it much intresting.

I would just like to request you that, it would be great if we can add/remove our customized feelings to emotion picker.

Because while using it, I have found that some of the feelings are not really I use, and also there are some which I would like to add.

And another usecase would be, particular frequently used links and tags can be made handy to add easily to the note and it can also used for nested tags, if we create separate section for each main tag.

I know that obsidian will auto suggest links and tags while adding but it would be easy to add many links and tags at a same time.

**Comment by dartungar** [comment]
That's a nice suggestion!
It was proposed in https://github.com/dartungar/obsidian-emotion-picker/issues/2, and I'll get to it when I'll find some time.
Cheers!
