### ISSUE TITLE
Feature Request: Link to emotion picker window in notes/templates

### ISSUE THREAD

**Issue by dannygrubb** [dartungar/obsidian-emotion-picker#8]
I'm liking this plugin so far. It would be nice to have the ability to put a link in a note template that when clicked will open the emotion picker window. An option to have the picked emotion replace the link or be inserted before/after the link would be nice as well. Thank you for your work!

**Comment by dartungar** [comment]
@dannygrubb I'm pretty sure you can do this with https://github.com/shabegom/buttons plugin! Make a button that calls the 'Open Emotion Picker' command when clicked.
