### ISSUE TITLE
Feature Request: The colored cirlces don't have a point?

### ISSUE THREAD

**Issue by Clastodon** [dartungar/obsidian-emotion-picker#9]
Hi I'm just exploring your plugin. I have a **Feature Request**. What's the point of the colored circles in the groupings? Why not have the opportunity to insert the Colored Circle in front of the Emotion? Otherwise it's just a word on a line, and doesn't stand out in any way. I know you have the option to identify it as a Tag or it's own page, but I don't need either of those. My use case would be to add an Emotion at the end of a statement, as I do an Emoticon. The emoticon stands out, as an icon. I would like this word to stand out too, and the colored circle would do this. Otherwise, what's the point of having the colored circles, or Dots if you will, in the groupings (in the Options)?
Actually I was looking for a Plugin that offered Emoticons, and yours is the nearest, so it does have great potential!
Many thanks!

**Comment by dartungar** [comment]
@Clastodon the colored circle is a color picker for underlinings of an emotion group.
